namespace MarkeDitor.Helpers;

/// <summary>
/// Curated set of emoji shortcodes for the picker dialog. Shortcodes are the
/// ones Markdown.Avalonia's <c>EmojiTable</c> understands, so what we insert
/// into the editor renders identically in the preview.
/// </summary>
public static class EmojiCatalog
{
    public readonly record struct Entry(string Shortcode, string Glyph, string Category);

    public static readonly Entry[] All =
    {
        // Smileys
        new(":smile:",            "😄", "Smileys"),
        new(":grin:",             "😁", "Smileys"),
        new(":laughing:",         "😆", "Smileys"),
        new(":joy:",              "😂", "Smileys"),
        new(":rofl:",             "🤣", "Smileys"),
        new(":blush:",            "😊", "Smileys"),
        new(":wink:",             "😉", "Smileys"),
        new(":sweat_smile:",      "😅", "Smileys"),
        new(":upside_down:",      "🙃", "Smileys"),
        new(":relaxed:",          "☺",  "Smileys"),
        new(":heart_eyes:",       "😍", "Smileys"),
        new(":kissing_heart:",    "😘", "Smileys"),
        new(":yum:",              "😋", "Smileys"),
        new(":sunglasses:",       "😎", "Smileys"),
        new(":nerd_face:",        "🤓", "Smileys"),
        new(":thinking:",         "🤔", "Smileys"),
        new(":expressionless:",   "😑", "Smileys"),
        new(":neutral_face:",     "😐", "Smileys"),
        new(":smirk:",            "😏", "Smileys"),
        new(":unamused:",         "😒", "Smileys"),
        new(":rolling_eyes:",     "🙄", "Smileys"),
        new(":astonished:",       "😲", "Smileys"),
        new(":flushed:",          "😳", "Smileys"),
        new(":sleeping:",         "😴", "Smileys"),
        new(":dizzy_face:",       "😵", "Smileys"),
        new(":mask:",             "😷", "Smileys"),
        new(":weary:",            "😩", "Smileys"),
        new(":pensive:",          "😔", "Smileys"),
        new(":disappointed:",     "😞", "Smileys"),
        new(":confused:",         "😕", "Smileys"),
        new(":worried:",          "😟", "Smileys"),
        new(":cry:",              "😢", "Smileys"),
        new(":sob:",              "😭", "Smileys"),
        new(":angry:",            "😠", "Smileys"),
        new(":rage:",             "😡", "Smileys"),
        new(":imp:",              "👿", "Smileys"),
        new(":smiling_imp:",      "😈", "Smileys"),
        new(":skull:",            "💀", "Smileys"),
        new(":poop:",             "💩", "Smileys"),
        new(":alien:",            "👽", "Smileys"),
        new(":robot:",            "🤖", "Smileys"),
        new(":ghost:",            "👻", "Smileys"),
        new(":clown:",            "🤡", "Smileys"),

        // People & body
        new(":+1:",               "👍", "People"),
        new(":-1:",               "👎", "People"),
        new(":ok_hand:",          "👌", "People"),
        new(":wave:",             "👋", "People"),
        new(":clap:",             "👏", "People"),
        new(":raised_hands:",     "🙌", "People"),
        new(":pray:",             "🙏", "People"),
        new(":muscle:",           "💪", "People"),
        new(":eyes:",             "👀", "People"),
        new(":point_up:",         "☝",  "People"),
        new(":point_right:",      "👉", "People"),
        new(":point_left:",       "👈", "People"),
        new(":point_down:",       "👇", "People"),

        // Hearts & symbols
        new(":heart:",            "❤",  "Symbols"),
        new(":yellow_heart:",     "💛", "Symbols"),
        new(":green_heart:",      "💚", "Symbols"),
        new(":blue_heart:",       "💙", "Symbols"),
        new(":purple_heart:",     "💜", "Symbols"),
        new(":broken_heart:",     "💔", "Symbols"),
        new(":sparkles:",         "✨", "Symbols"),
        new(":fire:",             "🔥", "Symbols"),
        new(":star:",             "⭐", "Symbols"),
        new(":zap:",              "⚡", "Symbols"),
        new(":boom:",             "💥", "Symbols"),
        new(":100:",              "💯", "Symbols"),
        new(":warning:",          "⚠",  "Symbols"),
        new(":exclamation:",      "❗", "Symbols"),
        new(":question:",         "❓", "Symbols"),
        new(":heavy_check_mark:", "✔",  "Symbols"),
        new(":white_check_mark:", "✅", "Symbols"),
        new(":x:",                "❌", "Symbols"),
        new(":no_entry:",         "⛔", "Symbols"),

        // Nature
        new(":sunny:",            "☀",  "Nature"),
        new(":cloud:",            "☁",  "Nature"),
        new(":umbrella:",         "☂",  "Nature"),
        new(":snowflake:",        "❄",  "Nature"),
        new(":rainbow:",          "🌈", "Nature"),

        // Animals
        new(":dog:",              "🐶", "Animals"),
        new(":cat:",              "🐱", "Animals"),
        new(":mouse:",            "🐭", "Animals"),
        new(":fox:",              "🦊", "Animals"),
        new(":penguin:",          "🐧", "Animals"),
        new(":bug:",              "🐛", "Animals"),
        new(":snake:",            "🐍", "Animals"),
        new(":fish:",             "🐟", "Animals"),
        new(":whale:",            "🐳", "Animals"),
        new(":turtle:",           "🐢", "Animals"),
        new(":bee:",              "🐝", "Animals"),

        // Food
        new(":coffee:",           "☕", "Food"),
        new(":beer:",             "🍺", "Food"),
        new(":wine_glass:",       "🍷", "Food"),
        new(":pizza:",            "🍕", "Food"),
        new(":cake:",             "🎂", "Food"),
        new(":apple:",            "🍎", "Food"),
        new(":hamburger:",        "🍔", "Food"),
        new(":taco:",             "🌮", "Food"),
        new(":sushi:",            "🍣", "Food"),
        new(":doughnut:",         "🍩", "Food"),

        // Travel & places
        new(":rocket:",           "🚀", "Travel"),
        new(":bicycle:",          "🚲", "Travel"),
        new(":car:",              "🚗", "Travel"),
        new(":bus:",              "🚌", "Travel"),
        new(":train:",            "🚆", "Travel"),
        new(":airplane:",         "✈",  "Travel"),

        // Activities & objects
        new(":soccer:",           "⚽", "Activities"),
        new(":basketball:",       "🏀", "Activities"),
        new(":football:",         "🏈", "Activities"),
        new(":baseball:",         "⚾", "Activities"),
        new(":tennis:",           "🎾", "Activities"),
        new(":trophy:",           "🏆", "Activities"),
        new(":crown:",            "👑", "Activities"),
        new(":gift:",             "🎁", "Activities"),
        new(":balloon:",          "🎈", "Activities"),

        // Tools & tech
        new(":gem:",              "💎", "Objects"),
        new(":bulb:",             "💡", "Objects"),
        new(":battery:",          "🔋", "Objects"),
        new(":computer:",         "💻", "Objects"),
        new(":iphone:",           "📱", "Objects"),
        new(":camera:",           "📷", "Objects"),
        new(":lock:",             "🔒", "Objects"),
        new(":key:",              "🔑", "Objects"),
        new(":hammer:",           "🔨", "Objects"),
        new(":wrench:",           "🔧", "Objects"),
        new(":mag:",              "🔍", "Objects"),
        new(":scissors:",         "✂",  "Objects"),
        new(":pencil2:",          "✏",  "Objects"),
        new(":memo:",             "📝", "Objects"),
        new(":book:",             "📖", "Objects"),
        new(":books:",            "📚", "Objects"),
        new(":calendar:",         "📅", "Objects"),
        new(":clock1:",           "🕐", "Objects"),
        new(":hourglass:",        "⏳", "Objects"),
        new(":moneybag:",         "💰", "Objects"),
        new(":dollar:",           "💵", "Objects"),
        new(":euro:",             "💶", "Objects"),
        new(":chart_with_upwards_trend:",   "📈", "Objects"),
        new(":chart_with_downwards_trend:", "📉", "Objects"),
        new(":mailbox:",          "📬", "Objects"),
        new(":email:",            "✉",  "Objects"),
        new(":pushpin:",          "📌", "Objects"),
        new(":paperclip:",        "📎", "Objects"),
        new(":file_folder:",      "📁", "Objects"),
        new(":bookmark:",         "🔖", "Objects"),
        new(":link:",             "🔗", "Objects"),
        new(":bell:",             "🔔", "Objects"),
    };
}
